Algoritmo "atividade55"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Mostra a tabuada do 8
// Autor(a)    : Eduardo
// Data atual  : 07/04/2023
Var
// Seção de Declarações das variáveis 
tabuada, contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 1 ate 10 faca
tabuada<-8*contador
escreval("8 X ",contador," = ",tabuada)
fimpara

Fimalgoritmo