Algoritmo "atividade51"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Mostra os números de 1 a 10 em ordem decrescente
// Autor(a)    : Eduardo
// Data atual  : 07/04/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 10 ate 1 passo -1 faca
escreval(contador)
fimpara

Fimalgoritmo