Algoritmo "atividade52"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Mostra os 10 primeiros números inteiros maiores que 100
// Autor(a)    : Eduardo
// Data atual  : 07/04/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 101 ate 111 faca
escreval(contador)
fimpara

Fimalgoritmo