Algoritmo "atividade58"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Mostra os numeros de 10 ate 1 com ENQUANTO e um CONTADOR
// Autor(a)    : Eduardo
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador<-11
enquanto contador <> 1 faca
contador<-contador-1
escreval(contador)
fimenquanto

Fimalgoritmo