Algoritmo "ManzanoPg66e"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Mostra os valores impares de 0 a 20
// Autor(a)    : Eduardo
// Data atual  : 13/04/2023
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para contador de 0 ate 20 passo 1 faca
  se contador mod 2 <> 0 entao
  escreval(contador)
  fimse
  fimpara

Fimalgoritmo